# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 147.75.82.23
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: rke-control-00
  user: root
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/workspace/ssh-keys/badams
  labels: {}
services:
  etcd:
    image: rancher/etcd:v3.0.17
    extra_args: {}
  kube-api:
    image: rancher/k8s:v1.8.7-rancher1-1
    extra_args: {}
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
  kube-controller:
    image: rancher/k8s:v1.8.7-rancher1-1
    extra_args: {}
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.7-rancher1-1
    extra_args: {}
  kubelet:
    image: rancher/k8s:v1.8.7-rancher1-1
    extra_args: {}
    cluster_domain: rke.rancher.local
    infra_container_image: rancher/pause-amd64:3.0
    cluster_dns_server: 10.233.0.3
    fail_swap_on: false
  kubeproxy:
    image: rancher/k8s:v1.8.7-rancher1-1
    extra_args: {}
network:
  plugin: flannel
  options: {}
authentication:
  strategy: x509
  options: {}
addons: ""
system_images:
  etcd: ""
  alpine: ""
  nginx_proxy: ""
  cert_downloader: ""
  kubernetes_services_sidecar: ""
  kubedns: ""
  dnsmasq: ""
  kubedns_sidecar: ""
  kubedns_autoscaler: ""
  kubernetes: ""
  flannel: ""
  flannel_cni: ""
  calico_node: ""
  calico_cni: ""
  calico_controllers: ""
  calico_ctl: ""
  canal_node: ""
  canal_cni: ""
  canal_flannel: ""
  wave_node: ""
  weave_cni: ""
  pod_infra_container: ""
ssh_key_path: ~/workspace/ssh-keys/badams
authorization:
  mode: none
  options: {}
ignore_docker_version: false
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
